FROM openeuler-20.03-lts-sp1:latest

RUN dnf clean expire-cache

RUN dnf -y install cmake gdb gcc gcc-c++ libstdc++-static ncurses ncurses-devel make python bash coreutils && \
    dnf -y clean all

RUN dnf -y install module-init-tools git openssl-devel bc bison flex dnf-plugins-core dosfstools parted wget device-mapper-multipath grep xz kpartx
RUN dnf -y install tar passwd diffutils
ENV SHELL=/bin/bash

ENTRYPOINT ["/bin/bash", "/work/build-image-common.sh"]

